variables:
  DOCKER_PRIVILEGED: "true"

test_kytos_mininet:
 image:
   name: kytos/nightly
 script:
  - for napp in storehouse of_core flow_manager topology of_lldp pathfinder mef_eline; do git clone https://github.com/kytos/$napp;  cd $napp; python3.6 setup.py develop; cd ..; done
  - kytosd
  - apt-get update && apt-get install -y python-pytest python-requests
  - pytest tests/
