version: '2.1'
services:
  kytos:
    image: amlight/kytos:latest
    privileged: true
    volumes:
      - "./kytos-init.sh:/kytos-init.sh"
      - "./tests:/tests"
    command:
      - /kytos-init.sh
#  mininet:
#      image: italovalcy/mininet:latest
#      privileged: true
#      links:
#        - "kytos"
#      command:
#        - /usr/bin/tail -f /dev/null
